const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({
    headless: false
  });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://app.friendify.ai/auth/login');
  await page.goto('https://friendify.ai/');
  await page.getByRole('banner').locator('div').filter({ hasText: 'FriendifyServicesBlogsAbout' }).first().click();
  await page.getByText('Login').click();
  await page.getByPlaceholder('Email...').click();
  await page.getByPlaceholder('Email...').fill('khauntc@gmail.com');
  await page.getByPlaceholder('Password...').click();
  await page.getByPlaceholder('Password...').fill('Chaukhau2000!');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('div').filter({ hasText: /^Từ "Xin chào" trong tiếng hàn là gì\?08:38 16\/10\/2024$/ }).getByRole('img').click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('link', { name: 'Contact' }).click();
  await page.getByRole('link', { name: 'Chat' }).click();
  await page.getByRole('link', { name: 'Feed' }).click();
  await page.getByRole('link', { name: 'Assist' }).click();
  await page.getByText('AskContactChatFeedAssist').first().click();
  await page.getByRole('link', { name: 'Assist' }).click();
  await page.locator('label').filter({ hasText: 'Upload File (Max 5MB .pdf)' }).locator('div').nth(1).click();
  await page.getByRole('button', { name: 'avatar' }).click();
  await page.getByRole('menuitem', { name: 'PDF Summary' }).click();
  await page.getByRole('button', { name: 'avatar' }).click();
  await page.getByRole('menuitem', { name: 'Guideline & Diamond' }).click();
  await page.getByRole('button', { name: 'avatar' }).click();
  await page.getByRole('link', { name: 'Assist' }).click();
  await page.locator('label').filter({ hasText: 'Upload File (Max 5MB .pdf)' }).locator('div').nth(1).click();
  await page.locator('body').setInputFiles('Tester - Đỗ Thúy Diệu - Playground - TopCV.pdf');
  await page.getByRole('button', { name: 'Start Summary' }).click();
  await page.goto('https://app.friendify.ai/assist/670fc4e134b49a9fe07756b8#docs');
  await page.getByText('Audio').click();
  await page.getByText('Docs').click();
  await page.locator('#scrollableDiv').getByRole('img').nth(1).click();
  await page.getByRole('img').click();
  await page.locator('#scrollableDiv').getByRole('img').nth(1).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.locator('#scrollableDiv').getByRole('img').nth(1).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByText('Audio').click();
  await page.getByText('Docs').click();
  await page.locator('div:nth-child(2) > div > .absolute > .w-\\[24px\\] > svg').click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.locator('.w-\\[24px\\]').first().click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.locator('#scrollableDiv').getByRole('img').nth(1).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.locator('#scrollableDiv').getByRole('img').nth(1).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByText('DocsAudioImage').click();
  await page.getByText('Docs').click();
  await page.locator('#scrollableDiv').getByRole('img').nth(1).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByText('Image', { exact: true }).click();
  await page.locator('label').filter({ hasText: 'Upload File (Max 5MB .png | .' }).locator('div').nth(1).click();
  await page.locator('body').setInputFiles('Image_4KB.png');
  await page.locator('div').filter({ hasText: /^Summary$/ }).getByRole('button').click();
  await page.getByRole('button', { name: 'Let\'s start' }).click();
  await page.goto('https://app.friendify.ai/assist/670fcd8334b49a9fe0775d33#image');
  await page.getByText('Image_4KB.png').click();
  await page.getByRole('link', { name: 'Ask' }).click();
  await page.getByRole('link', { name: 'Assist' }).click();
  await page.getByText('Audio').click();
  await page.getByRole('link', { name: 'Ask' }).click();
  await page.getByRole('link', { name: 'Assist' }).click();
  await page.getByText('Image', { exact: true }).click();
  await page.locator('#scrollableDiv').getByRole('img').nth(1).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.locator('.w-\\[24px\\]').click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByText('Blurry or poor-quality images').click();
  await page.locator('body').setInputFiles('Image_6MB.jpg');
  await page.getByText('Blurry or poor-quality images').click();
  await page.locator('body').setInputFiles('Image_4KB.png');
  await page.locator('div').filter({ hasText: /^Remove object$/ }).getByRole('button').click();
  await page.getByRole('button', { name: 'Let\'s start' }).click();
  await page.locator('canvas').nth(1).click({
    position: {
      x: 172,
      y: 84
    }
  });
  await page.locator('canvas').nth(1).click({
    position: {
      x: 439,
      y: 94
    }
  });
  await page.getByRole('button', { name: 'Clean •' }).click();
  await page.getByText('Audio').click();
  await page.getByText('Image').click();
  await page.locator('#scrollableDiv').getByRole('img').click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.goto('https://app.friendify.ai/assist#image');
  await page.getByText('Audio').click();
  await page.getByText('Image').click();
  await page.locator('div').filter({ hasText: /^Upload your image$/ }).locator('img').click();
  await page.getByText('Upload File (Max 5MB .png | .').click();
  await page.locator('body').setInputFiles('Image_2KB.jpg');
  await page.locator('div').filter({ hasText: /^Remove text$/ }).getByRole('button').click();
  await page.getByRole('button', { name: 'Let\'s start' }).click();
  await page.getByText('Audio').click();
  await page.getByText('Image').click();
  await page.locator('.w-\\[24px\\]').click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByText('Audio').click();
  await page.getByText('Image').click();
  await page.getByRole('button', { name: 'diamond-icon' }).click();
  await page.getByLabel('580').click();
  await page.locator('[id="headlessui-menu-button-\\:r1\\:"]').click();
  await page.getByRole('button', { name: 'avatar' }).click();
  await page.getByRole('menuitem', { name: 'History' }).click();
  await page.getByRole('link', { name: 'Feed', exact: true }).click();
  await page.getByRole('link', { name: 'Chat' }).click();
  await page.getByRole('link', { name: 'Contact' }).click();
  await page.getByRole('link', { name: 'Friend Request' }).click();
  await page.getByRole('link', { name: 'Contact' }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Contact$/ }).getByRole('paragraph').click();
  await page.getByRole('link', { name: 'Chat' }).click();
  await page.getByText('Huy Thien', { exact: true }).click();
  await page.getByRole('link', { name: 'Ask' }).click();
  await page.getByRole('link', { name: 'logo' }).click();
  await page.getByRole('button', { name: 'avatar' }).click();
  await page.getByText('AskContactChatFeedAssist').first().click();
  await page.getByRole('link', { name: 'Contact' }).click();
  await page.getByRole('link', { name: 'Ask' }).click();
  await page.getByRole('link', { name: 'logo' }).click();
  await page.getByText('AskContactChatFeedAssist').first().click();
  await page.getByRole('link', { name: 'Chat' }).click();
  await page.getByRole('link', { name: 'Chat' }).click();
  await page.getByRole('link', { name: 'Ask' }).click();
  await page.getByRole('link', { name: 'logo' }).click();
  await page.getByRole('link', { name: 'New chat' }).click();
  await page.getByRole('main').getByRole('link').first().click();
  await page.getByRole('link', { name: 'logo' }).click();
  await page.getByRole('main').getByRole('link').first().click();
  await page.getByRole('link', { name: 'logo' }).click();
  await page.getByRole('main').getByRole('link').first().click();
  await page.getByRole('link', { name: 'AI Generate Image Create new' }).click();
  await page.getByPlaceholder('Describe your image...').click();
  await page.getByPlaceholder('Describe your image...').fill('ta');
  await page.getByPlaceholder('Describe your image...').press('Shift+ArrowLeft');
  await page.getByPlaceholder('Describe your image...').fill('');
  await page.getByPlaceholder('Describe your image...').press('CapsLock');
  await page.getByPlaceholder('Describe your image...').fill('T');
  await page.getByPlaceholder('Describe your image...').press('CapsLock');
  await page.getByPlaceholder('Describe your image...').fill('Tao anh con meo');
  await page.getByPlaceholder('Describe your image...').click();
  await page.getByPlaceholder('Describe your image...').click();
  await page.getByPlaceholder('Describe your image...').press('ControlOrMeta+a');
  await page.getByPlaceholder('Describe your image...').press('ControlOrMeta+c');
  await page.getByPlaceholder('Describe your image...').press('ControlOrMeta+c');
  await page.getByRole('link', { name: 'logo' }).click();
  await page.getByRole('main').getByRole('link').first().click();
  await page.getByRole('link', { name: 'AI Generate Image Create new' }).click();
  await page.getByPlaceholder('Describe your image...').click({
    modifiers: ['ControlOrMeta']
  });
  await page.getByPlaceholder('Describe your image...').fill('Tao anh con meo');
  await page.getByRole('button', { name: 'Generate' }).click();
  await page.getByRole('img', { name: 'Generated Image' }).nth(1).click();
  await page.getByRole('button', { name: 'Pro •' }).click();
  await page.getByPlaceholder('Describe your image...').click();
  await page.getByPlaceholder('Describe your image...').fill('Tao ảnh con mèo');
  await page.getByRole('button', { name: 'Generate' }).click();
  await page.getByRole('img', { name: 'Generated Image' }).nth(2).click();
  await page.getByPlaceholder('Describe your image...').click();
  await page.getByPlaceholder('Describe your image...').fill('d');
  await page.getByRole('button', { name: 'Generate' }).click();
  await page.getByPlaceholder('Describe your image...').click();
  await page.getByPlaceholder('Describe your image...').fill('f');
  await page.getByRole('button', { name: 'Generate' }).click();
  await page.getByText('Standard • 5 Pro •').click();
  await page.locator('div').filter({ hasText: /^AI Generate ImageNew chat$/ }).getByRole('link').first().click();
  await page.getByRole('link', { name: 'AI Generate Image Create new' }).click();
  await page.getByRole('link', { name: 'Contact' }).click();
  await page.getByText('AskContactChatFeedAssist').first().click();
  await page.getByRole('link', { name: 'Assist' }).click();
  await page.getByText('DocsAudioImageUpload File (').click();
  await page.getByText('DocsAudioImageUpload File (').click();
  await page.getByText('Image', { exact: true }).click();
  await page.getByText('Audio').click();
  await page.getByText('AskContactChatFeedAssist425AskContactChatFeedAssist').click();
  await page.getByRole('link', { name: 'Ask' }).click();
  await page.getByRole('link', { name: 'AI Generate Image Create new' }).click();
  await page.getByRole('link', { name: 'Chat', exact: true }).click();
  await page.getByRole('link', { name: 'Feed' }).click();
  await page.getByRole('link', { name: 'Assist' }).click();
  await page.getByText('Image', { exact: true }).click();
  await page.getByRole('link', { name: 'logo' }).click();
  await page.getByText('AskContactChatFeedAssist412AskContactChatFeedAssist').click();
  await page.getByText('AskContactChatFeedAssist').first().click();
  await page.getByRole('link', { name: 'Chat' }).dblclick();
  await page.getByRole('link', { name: 'logo' }).click();
  await page.getByText('AI Chat GPTNew chat').click();
  await page.getByRole('link', { name: 'New chat' }).click();
  await page.getByRole('link', { name: 'New chat' }).click();
  await page.getByRole('link', { name: 'New chat' }).click();
  await page.getByRole('link', { name: 'New chat' }).click();
  await page.getByRole('main').getByRole('link').first().click();
  await page.getByRole('link', { name: 'AI Generate Image Create new' }).click();
  await page.getByRole('link', { name: 'logo' }).click();
  await page.getByRole('main').getByRole('link').first().click();
  await page.getByRole('link', { name: 'AI Generate Image Create new' }).click();
  await page.getByRole('link', { name: 'logo' }).click();
  await page.getByRole('main').getByRole('link').first().click();
  await page.getByRole('link', { name: 'AI Generate Image Create new' }).click();
  await page.getByText('AskContactChatFeedAssist').first().click();
  await page.getByRole('link', { name: 'Ask' }).click();
  await page.getByRole('link', { name: 'Chat', exact: true }).click();
  await page.getByRole('link', { name: 'Ask' }).click();
  await page.getByRole('link', { name: 'logo' }).click();
  await page.getByRole('link', { name: 'Chat', exact: true }).click();
  await page.getByRole('link', { name: 'Ask' }).click();
  await page.getByRole('link', { name: 'AI Generate Image Create new' }).click();
  await page.getByRole('button', { name: 'avatar' }).click();
  await page.getByText('Logout').click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('link', { name: 'Log In' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.locator('div').filter({ hasText: /^Continue with Google$/ }).nth(1).click();
  const page1 = await page1Promise;
  await page1.getByLabel('Email or phone').fill('chaukhau2000@playgroundvina.com');
  await page1.getByRole('button', { name: 'Next' }).click();
  await page1.getByLabel('Enter your password').fill('n2ErJyTj2g9K9mN&');
  await page1.getByRole('button', { name: 'Next' }).click();
  await page1.getByRole('button', { name: 'Tôi hiểu' }).click();
  await page1.getByLabel('Tạo mật khẩu').press('ControlOrMeta+a');
  await page1.getByLabel('Tạo mật khẩu').fill('Khautester2000');
  await page1.getByLabel('Xác nhận mật khẩu').click();
  await page1.getByLabel('Xác nhận mật khẩu').fill('Khautester2000');
  await page1.getByRole('button', { name: 'Đổi mật khẩu' }).click();
  await page1.getByRole('button', { name: 'Tiếp tục' }).click();
  await page1.close();
  await page.getByRole('button', { name: 'Skip' }).click();
  await page.getByRole('button', { name: 'avatar' }).click();
  await page.getByText('Logout').click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('link', { name: 'Log In' }).click();
  const page2Promise = page.waitForEvent('popup');
  await page.getByText('Continue with Google').click();
  const page2 = await page2Promise;
  await page2.close();
  await page.getByRole('button', { name: 'Skip' }).click();
  await page.getByRole('button', { name: 'avatar' }).click();
  await page.getByText('Logout').click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('link', { name: 'Log In' }).click();
  await page.getByPlaceholder('Email...').click();
  await page.getByPlaceholder('Email...').fill('khauntc@gmail.com');
  await page.getByPlaceholder('Password...').click({
    modifiers: ['ControlOrMeta']
  });
  await page.getByPlaceholder('Password...').fill('Chaukhau2000!');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'avatar' }).click();
  await page.getByText('Logout').click();
  await page.getByRole('button', { name: 'Confirm' }).click();

  // ---------------------
  await context.close();
  await browser.close();
})();