const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({
    headless: false
  });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://music.busai.me/');
  await page.getByText('✖').click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Login' }).click();
  const page1 = await page1Promise;
  const page2Promise = page1.waitForEvent('popup');
  await page1.getByRole('button', { name: 'Login with telegram' }).click();
  const page2 = await page2Promise;
  await page1.getByRole('button', { name: 'Login with telegram' }).click();
  await page2.locator('#login-phone').click();
  await page2.locator('#login-phone').fill('339824931');
  await page2.getByRole('button', { name: 'Next' }).click();
  await page2.goto('https://oauth.telegram.org/auth/push?bot_id=7098503440&origin=https%3A%2F%2Fsso.busai.me&request_access=true&return_to=https%3A%2F%2Fsso.busai.me%2Fauth');
  await page2.close();
  await page1.close();
  await page.goto('https://music.busai.me/discover');
  await page.getByText('✖').click();
  await page.getByRole('img', { name: '.' }).click();
  await page.getByRole('img', { name: '.' }).click();
  await page.getByRole('img', { name: '.' }).dblclick();
  await page.getByRole('link', { name: 'Discover' }).click();
  await page.getByRole('link', { name: 'Discover' }).click();
  await page.locator('li').filter({ hasText: 'Fantasy Trip EtherealLullaby09' }).nth(1).click();
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.getByRole('link', { name: 'Magic Way to the Stars 🌟 (K-' }).click();
  await page.locator('#play-pause').click();
  await page.locator('#play-pause').click();
  await page.goto('https://music.busai.me/track/SjIUOuk2N7Abghz/play');
  await page.getByText('✖').click();
  await page.getByRole('img', { name: '.' }).click();
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.getByRole('link', { name: 'I Just Bust A Nut In My Pants' }).click();
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.getByRole('link', { name: 'Crater Lullaby Panto' }).click();
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.getByRole('link', { name: 'Analog House dontcallmeBryan' }).click();
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.getByRole('link', { name: 'Spring Preppy_gurl' }).click();
  const page3Promise = page.waitForEvent('popup');
  await page.locator('a').first().click();
  const page3 = await page3Promise;
  await page3.close();
  await page.getByRole('link', { name: 'New Music' }).click();
  await page.locator('.cover_art > a').first().click();
  await page.locator('.emojionearea-editor').first().click();
  await page.locator('.emojionearea-editor').first().press('CapsLock');
  await page.locator('.emojionearea-editor').first().fill('B');
  await page.locator('.emojionearea-editor').first().press('CapsLock');
  await page.getByText('B', { exact: true }).fill('');
  await page.getByText('Comment 1').fill('Comment 1\n\n');
  await page.getByRole('link', { name: 'New Music' }).click();
  await page.locator('div:nth-child(2) > .track_list > .track > .cover_art > a').click();
  await page.locator('.emojionearea-editor').first().click();
  await page.locator('.emojionearea-editor').first().press('CapsLock');
  await page.locator('.emojionearea-editor').first().fill('C');
  await page.locator('.emojionearea-editor').first().press('CapsLock');
  await page.getByText('C', { exact: true }).fill('Comment 2\n\n');
  await page.getByRole('link', { name: 'New Music' }).click();
  await page.locator('div:nth-child(3) > .track_list > .track > .cover_art > a').first().click();
  await page.locator('.emojionearea-editor').first().click();
  await page.getByRole('link', { name: 'New Music' }).click();
  await page.locator('div:nth-child(3) > .track_list > .track > .cover_art > a').first().click();
  await page.locator('.emojionearea-editor').first().click();
  await page.locator('.emojionearea-editor').first().press('CapsLock');
  await page.locator('.emojionearea-editor').first().fill('C');
  await page.locator('.emojionearea-editor').first().press('CapsLock');
  await page.getByText('C', { exact: true }).fill('Comment 3\n\n');
  await page.getByRole('link', { name: 'New Music' }).click();
  await page.locator('div:nth-child(4) > .track_list > .track > .cover_art > a').click();
  await page.locator('.emojionearea-editor').first().click();
  await page.locator('.emojionearea-editor').first().press('CapsLock');
  await page.locator('.emojionearea-editor').first().fill('C');
  await page.locator('.emojionearea-editor').first().press('CapsLock');
  await page.getByText('C', { exact: true }).fill('Comment 4\n\n');
  await page.getByRole('link', { name: 'New Music' }).click();
  await page.locator('div:nth-child(5) > .track_list > .track > .cover_art > a').click();
  await page.locator('.emojionearea-editor').first().click();
  await page.locator('.emojionearea-editor').first().press('CapsLock');
  await page.locator('.emojionearea-editor').first().fill('C');
  await page.locator('.emojionearea-editor').first().press('CapsLock');
  await page.getByText('C', { exact: true }).fill('Comment 5\n\n');
  await page.getByRole('link', { name: 'New Music' }).click();
  await page.locator('.cover_art > a').first().click();
  await page.locator('.emojionearea-editor').first().click();
  await page.locator('.emojionearea-editor').first().fill('Comment 1\n\n');
  await page.getByRole('link', { name: 'Load More' }).click();
  await page.locator('.emojionearea-editor').first().click();
  await page.locator('.emojionearea-editor').first().fill('Comment 12\n\n');
  await page.goto('https://music.busai.me/track/JeJfbUDGb8BB37b/play');
  await page.getByText('✖').click();
  await page.getByRole('link', { name: 'New Music' }).click();
  await page.locator('.cover_art > a').first().click();
  await page.locator('.emojionearea-editor').first().click();
  await page.locator('.emojionearea-editor').first().fill('d\n\n');
  await page.getByTitle('Delete comment').click();
  await page.getByRole('button', { name: 'Delete' }).click();
  await page.locator('.emojionearea-editor').click();
  await page.locator('.emojionearea-editor').fill('j\n\n');
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.getByRole('link', { name: 'Discover' }).click();
  await page.locator('div:nth-child(5) > .owl-carousel > .owl-stage-outer > .owl-stage > div > .track_list > .track > .cover_art > a').first().click();
  await page.getByText('✖').click();
  await page.getByRole('link', { name: 'Discover' }).click();
  await page.locator('div:nth-child(5) > .owl-carousel > .owl-stage-outer > .owl-stage > div > .track_list > .track > .cover_art > a').first().click();
  await page.getByRole('button', { name: 'Liked' }).click();
  await page.getByRole('button', { name: 'Like', exact: true }).click();
  await page.getByRole('button', { name: 'Liked' }).click();
  await page.getByRole('link', { name: 'Discover' }).click();
  await page.locator('div:nth-child(2) > .track_list > .track > .cover_art > a').first().click();
  await page.getByRole('button', { name: 'Liked' }).click();
  await page.getByRole('button', { name: 'Like', exact: true }).click();
  await page.getByRole('button', { name: 'Liked' }).click();
  await page.getByRole('link', { name: 'Discover' }).click();
  await page.locator('div:nth-child(5) > .owl-carousel > .owl-stage-outer > .owl-stage > div:nth-child(3) > .track_list > .track > .cover_art > a').click();
  await page.locator('div:nth-child(5) > .owl-carousel > .owl-stage-outer > .owl-stage > div:nth-child(3) > .track_list > .track > .cover_art > a').click();
  await page.getByRole('button', { name: 'Liked' }).click();
  await page.getByRole('button', { name: 'Like', exact: true }).click();
  await page.getByRole('button', { name: 'Liked' }).click();
  await page.getByRole('link', { name: 'Discover' }).click();
  await page.goto('https://music.busai.me/discover');
  await page.getByText('✖').click();
  await page.locator('div:nth-child(5) > .owl-carousel > .owl-stage-outer > .owl-stage > div:nth-child(4) > .track_list > .track > .cover_art > a').click();
  await page.getByRole('button', { name: 'Like', exact: true }).click();
  await page.getByRole('button', { name: 'Liked' }).click();
  await page.getByRole('link', { name: 'Discover' }).click();
  await page.goto('https://music.busai.me/discover');
  await page.getByText('✖').click();
  await page.locator('div:nth-child(5) > .owl-carousel > .owl-stage-outer > .owl-stage > div:nth-child(5) > .track_list > .track > .cover_art > a').click();
  await page.getByText('✖').click();
  await page.getByRole('button', { name: 'Like', exact: true }).click();
  await page.getByRole('button', { name: 'Liked' }).click();
  await page.locator('div:nth-child(5) > .owl-carousel > .owl-stage-outer > .owl-stage > div > .track_list > .track > .cover_art > a').first().click();
  await page.goto('https://music.busai.me/discover');
  await page.getByText('✖').click();
  await page.locator('div:nth-child(5) > .owl-carousel > .owl-stage-outer > .owl-stage > div > .track_list > .track').first().click();
  await page.locator('.ss_sub_body > div > a').click();
  await page.getByRole('link', { name: 'howlingWolf49', exact: true }).first().click();
  await page.getByText('✖').click();
  await page.getByRole('link', { name: 'Discover' }).click();
  await page.goto('https://music.busai.me/discover');
  await page.getByText('✖').click();
  await page.getByRole('link', { name: 'Sweet Whisper' }).nth(1).click();
  await page.getByRole('link', { name: 'Verloren tijd 2.mp3' }).first().click();
  await page.goto('https://music.busai.me/discover');
  await page.getByText('✖').click();
  await page.getByRole('link', { name: 'Eu Sou um Monopóla' }).first().click();
  await page.getByRole('link', { name: 'Discover' }).click();
  await page.getByText('✖').click();
  await page.getByRole('link', { name: 'Drum beat in heart' }).first().click();
  await page.getByRole('link', { name: 'Discover' }).click();
  await page.goto('https://music.busai.me/discover');
  await page.getByText('✖').click();
  await page.getByRole('link', { name: 'Spiritual Tears.mp3', exact: true }).click();
  await page.getByRole('link', { name: 'Discover' }).click();
  await page.getByText('✖').click();
  await page.getByRole('link', { name: 'Sweet Whisper' }).nth(1).click();
  await page.goto('https://music.busai.me/discover');
  await page.getByText('✖').click();
  await page.getByRole('heading', { name: 'New Releases Show all' }).getByRole('link').click();
  await page.goto('https://music.busai.me/new_music');
  await page.getByText('✖').click();
  await page.getByRole('link', { name: 'Discover' }).click();
  await page.getByRole('link', { name: 'Albums' }).click();
  await page.getByText('✖').click();
  await page.getByRole('link', { name: 'New Music' }).click();
  await page.getByRole('link', { name: 'New Music' }).click();
  await page.getByRole('link', { name: 'New Music' }).click();
  await page.locator('.cover_art > a').first().click();
  await page.locator('.pause_btn > img').click();
  await page.getByRole('link', { name: 'New Music' }).click();
  await page.getByRole('link', { name: 'Playlists', exact: true }).click();
  await page.getByRole('link', { name: 'Bustling energy' }).first().click();
  await page.getByRole('link', { name: 'Discover' }).click();
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.getByText('✖').click();
  await page.getByRole('link', { name: 'New Music' }).click();
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.getByRole('link', { name: 'Magic Way to the Stars 🌟 (K-' }).click();
  await page.getByRole('button', { name: 'DisLike' }).click();
  await page.getByRole('button', { name: 'Disliked' }).click();
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.getByRole('link', { name: 'I Just Bust A Nut In My Pants' }).click();
  await page.getByRole('button', { name: 'DisLike' }).click();
  await page.getByRole('button', { name: 'Disliked' }).click();
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.getByRole('link', { name: 'Crater Lullaby Panto' }).click();
  await page.getByRole('button', { name: 'DisLike' }).click();
  await page.getByRole('button', { name: 'Disliked' }).click();
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.getByRole('link', { name: 'Analog House dontcallmeBryan' }).click();
  await page.getByRole('button', { name: 'DisLike' }).click();
  await page.getByRole('button', { name: 'Disliked' }).click();
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.getByRole('link', { name: 'Spring Preppy_gurl' }).click();
  await page.getByRole('button', { name: 'DisLike' }).click();
  await page.getByRole('button', { name: 'Disliked' }).click();
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.getByRole('link', { name: 'Nose Dive | Electric No-Lyric' }).click();
  await page.getByRole('button', { name: 'Re Post' }).click();
  await page.getByRole('button', { name: 'Re Post' }).click();
  await page.getByRole('button', { name: 'Re Post' }).click();
  await page.getByText('Your post has been').click();
  await page.getByRole('button', { name: 'Re Post' }).click();
  await page.getByLabel('Your post has been').locator('path').click();
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.getByRole('link', { name: 'sushi in the Kitchen' }).click();
  await page.getByRole('button', { name: 'Re Post' }).click();
  await page.getByLabel('Your post has been').locator('path').click();
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.getByRole('link', { name: 'Supercalifragilisticexpialidocious SynthSun88' }).click();
  await page.getByRole('button', { name: 'Re Post' }).click();
  await page.getByLabel('Your post has been').getByRole('img').click();
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.getByRole('link', { name: 'Yogi Music | Pop Drxke79' }).click();
  await page.getByRole('button', { name: 'Re Post' }).click();
  await page.getByLabel('Your post has been').locator('path').click();
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.getByRole('link', { name: 'Love Dose VinylRemedy24' }).click();
  await page.getByRole('button', { name: 'Re Post' }).click();
  await page.getByLabel('Your post has been').locator('path').click();
  await page.getByRole('link', { name: 'New Music' }).click();
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.locator('li').filter({ hasText: '1 Magic Way to the Stars 🌟 (' }).getByRole('img').nth(2).click();
  await page.locator('li').filter({ hasText: '1 Magic Way to the Stars 🌟 (' }).locator('path').nth(1).click();
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.getByRole('link', { name: 'Magic Way to the Stars 🌟 (K-' }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Download' }).click();
  const download = await downloadPromise;
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.getByRole('link', { name: 'I Just Bust A Nut In My Pants' }).click();
  const download1Promise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Download' }).click();
  const download1 = await download1Promise;
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.getByRole('link', { name: 'Crater Lullaby Panto' }).click();
  const download2Promise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Download' }).click();
  const download2 = await download2Promise;
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.getByRole('link', { name: 'Analog House dontcallmeBryan' }).click();
  const download3Promise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Download' }).click();
  const download3 = await download3Promise;
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.getByRole('link', { name: 'Spring Preppy_gurl' }).click();
  const download4Promise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Download' }).click();
  const download4 = await download4Promise;
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.locator('li').filter({ hasText: 'Nose Dive | Electric No-Lyric' }).nth(1).click();
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.locator('li').filter({ hasText: 'sushi in the Kitchen' }).nth(1).click();
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.getByRole('link', { name: 'Supercalifragilisticexpialidocious SynthSun88' }).click();
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.locator('li').filter({ hasText: 'Supercalifragilisticexpialidocious SynthSun88' }).nth(1).click();
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.locator('li').filter({ hasText: 'Yogi Music | Pop Drxke79' }).nth(1).click();
  await page.getByText('✖').click();
  await page.getByRole('link', { name: 'Top Music' }).click();
  await page.locator('li').filter({ hasText: 'Love Dose VinylRemedy24' }).nth(1).click();
  await page.close();

  // ---------------------
  await context.close();
  await browser.close();
})();