pipeline {
    agent {
        docker { image 'mcr.microsoft.com/playwright:v1.47.2-jammy' }
    }
    environment {
        REPO_NAME = 'Tongram'
        FILE_SH = 'TG_Auto.sh'
        FILE_BAT = 'TG_Auto.bat'
        SERVER_PATH = "Automation_With_Playwright/${REPO_NAME}"
        SERVER_PROJECT = "Automation_With_Playwright"
        BRANCH_NAME = 'master'
        JENKINS_CREDENTIALS_ID = '6f5eb65d-9009-4049-8b13-1becf88d77cb'
        chatId = '-1002308985537'  
        botToken = '8085219018:AAHSTNao6k9OucZc15LQ476N-039N8NR7WI'
        // No need, because already setup Jenkins Credentials (usernamePassword credential)
        // GITHUB_USER = 'chaukhau2000@gmail.com'
        // GITHUB_TOKEN = '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'
    }
    triggers {
        cron('0 19 * * *')
    }

    stages {
        stage('CI: Checkout Code') {
            steps {
                script {
                    def changes = sh(script: "git diff --name-only origin/${BRANCH_NAME}..${BRANCH_NAME}", returnStdout: true).trim()
                    if (changes) {
                        echo "Changes detected. Checking out code..."
                        withCredentials([usernamePassword(credentialsId: "${JENKINS_CREDENTIALS_ID}", usernameVariable: 'GITHUB_USER', passwordVariable: 'GITHUB_TOKEN')]) {
                            git branch: "${BRANCH_NAME}",
                                credentialsId: "${JENKINS_CREDENTIALS_ID}",
                                url: "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/chaukhau19/Automation_With_Playwright.git"
                        }
                        echo "Code checked out from ${BRANCH_NAME}"
                    } else {
                        echo "No changes detected. Skipping checkout."
                    }

                    env.REPO_PATH = sh(script: "find . -type d -name '${REPO_NAME}'", returnStdout: true).trim()
                    if (env.REPO_PATH) {
                        echo "Found ${REPO_NAME} at: ${env.REPO_PATH}"
                    } else {
                        error "Repository directory ${REPO_NAME} not found."
                    }
                }
                sh """
                    cd ${env.REPO_PATH}
                    pwd
                    ls -la
                """
            }
        }

        stage('Setup Dependencies') {
            steps {
                echo 'Setting up dependencies'
                script {
                    sh """
                        cd ${env.REPO_PATH}

                        if [ -d "node_modules" ]; then
                            echo "node_modules already exists. Checking Playwright version..."
                            chmod +x node_modules/.bin/playwright

                            if npx playwright --version; then
                                echo "Playwright is already installed. Skipping installation."
                            else
                                echo "Playwright is not installed. Installing..."
                                rm -rf node_modules package-lock.json
                                npm install
                                npx playwright install
                                npm install @playwright/test@latest
                            fi
                        else
                            echo "node_modules does not exist. Installing dependencies..."
                            npm install
                            npx playwright install
                            npm install @playwright/test@latest
                        fi
                    """
                }
            }
        }

        stage('CD: Run Tests') {
            steps {
                echo 'Starting Tests'
                script {
                    if (isUnix()) {
                        sh """
                            cd ${env.REPO_PATH}
                            chmod +x ${FILE_SH} 
                            ./${FILE_SH}
                        """
                    } else {
                        bat """
                            cd ${env.REPO_PATH}
                            ${FILE_BAT}
                        """
                    }
                }
                echo "Tests executed"
            }
        }

        stage('Archive Test Results') {
            steps {
                archiveArtifacts artifacts: '**/playwright-report/**/*', allowEmptyArchive: true
                echo 'Test results archived.'
            }
        }
    }

    post {
        success {
            script {
                def status = currentBuild.result ?: 'SUCCESS'
                echo "All test cases passed. Build status: ${status}"
                cleanTemporaryFolder()

                def message = """
                🔧 Jenkins Build for ${REPO_NAME} #${env.BUILD_NUMBER}
                ✅ Status: ${currentBuild.currentResult}
                🕒 Time: ${currentBuild.durationString}
                🔗 Link: ${env.BUILD_URL}
                """

                sendMessageToTelegram(message)
            }
        }

        failure {
            script {
                def status = currentBuild.result ?: 'FAILURE'
                echo "Some test cases failed. Build status: ${status}"
                cleanTemporaryFolder()

                def message = """
                🔧 Jenkins Build for ${REPO_NAME} #${env.BUILD_NUMBER}
                ❌ Status: ${currentBuild.currentResult}
                🕒 Time: ${currentBuild.durationString}
                🔗 Link: ${env.BUILD_URL}
                """
                sendMessageToTelegram(message)
            }
        }
    }
}

def cleanTemporaryFolder() {
    if (isUnix()) {
        if (fileExists("${SERVER_PATH}/temp")) {
            sh "rm -rf ${SERVER_PATH}/temp/*"
        } else {
            echo "Temporary folder does not exist."
        }
    } else {
        bat "if exist ${SERVER_PATH}\\temp\\* del /Q ${SERVER_PATH}\\temp\\*"
    }
}

def sendMessageToTelegram(message) {
    sh "curl -s -X POST https://api.telegram.org/bot${botToken}/sendMessage -d chat_id=${chatId} -d text='${message}'"
}
