pipeline {
    agent {
        docker { image 'node:18.20.4-alpine3.20' }
    }
    environment {
        GITHUB_URL = 'https://github.com/chaukhau19/Automation_With_Playwright.git'
        REPO_NAME = 'BusaiGPT'  
        FILE_SH = 'BusaiGPT/BS_Auto.sh'
        FILE_BAT = 'BusaiGPT/BS_Auto.bat'
        SERVER_PATH = "Automation_With_Playwright/${REPO_NAME}"
        BRANCH_NAME = 'master'
        FOUND_SCRIPT_PATH = ''
    }
    stages {
        stage('Checkout Code') {
            steps {
                git(branch: "${BRANCH_NAME}", url: "${GITHUB_URL}")
                echo "Code checked out from ${BRANCH_NAME}"
            }
        }
        
        stage('Search for BS_Auto.sh Script') {
            steps {
                echo 'Searching for BS_Auto.sh'
                script {
                    // Sử dụng find để tìm đường dẫn đầy đủ của file
                    def findCommand = 'find . -name "BS_Auto.sh"'
                    def findResult = sh(script: findCommand, returnStdout: true).trim()
                    
                    if (findResult) {
                        echo "BS_Auto.sh found at: ${findResult}"
                        // Lưu đường dẫn của script vào biến môi trường
                        env.FOUND_SCRIPT_PATH = findResult
                    } else {
                        echo "BS_Auto.sh not found, skipping tests."
                    }
                }
            }
        }

        stage('CI: Run Tests') {
            steps {
                echo 'Starting Tests'
                script {
                    if (isUnix()) {
                        if (env.FOUND_SCRIPT_PATH) {
                            echo "Running on Unix environment"
                            sh "chmod +x ${env.FOUND_SCRIPT_PATH}"  // Thực hiện chmod cho script
                            sh "${env.FOUND_SCRIPT_PATH}"          // Chạy script từ vị trí tìm được
                        } else {
                            echo "No BS_Auto.sh script found, skipping execution."
                        }
                    } else {
                        echo "Running on Windows environment"
                        bat "${FILE_BAT}"
                    }
                }
                echo "Tests executed"
            }
        }

        stage('Archive Test Results') {
            steps {
                archiveArtifacts(artifacts: './BusaiGPT/playwright-report/**/*', allowEmptyArchive: true)
                echo 'Test results archived.'
            }
        }
    }

    post {
        always {
            script {
                def status = currentBuild.result ?: 'SUCCESS'
                echo "Build status: ${status}"
                if (isUnix()) {
                    sh "rm -rf ${SERVER_PATH}/temp/*"
                } else {
                    bat "del /Q ${SERVER_PATH}\\temp\\*"
                }
            }
        }
    }
}
